version: "3.9"

networks:
  apologym:
    driver: bridge

volumes:
  db-data:

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04
    container_name: apologym-sql
    restart: always
    ports:
      - "8008:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Saltamontes_007
      - apologym
    volumes:
      - db-data:/var/opt/mssql

  api:
    container_name: apologym-api
    build:
      context: .
      dockerfile: ApoloGym.API/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ApoloGymDB;User Id=sa;Password=Saltamontes_007;TrustServerCertificate=True;
    networks:
      - apologym